#ifndef EXTI_CONFIG_H
#define EXTI_CONFIG_H

/*
   Options:
   EXTI_u8_LOW_LEVEL
   EXTI_u8_ON_CHANGE
   EXTI_u8_FALLING_EDGE
   EXTI_u8_RISING_EDGE
*/

#define EXTI0_u8_SENSE_CONTROL   EXTI_u8_RISING_EDGE
#define EXTI1_u8_SENSE_CONTROL   EXTI_u8_RISING_EDGE

#endif
